name: Deploy to Azure

on:
  push:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: "your-app-name"      # 替换为你的Azure应用名称
  RESOURCE_GROUP: "your-resource-group"   # 替换为你的资源组名称
  IMAGE_NAME: "charge-station"            # Docker镜像名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置Java 8环境
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      # 3. 使用Maven构建项目
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. 构建Docker镜像
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      # 5. 登录Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6. 部署到Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          images: ${{ env.IMAGE_NAME }}
